name = "mealviewer-bridge"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "mealviewer-bridge.wishicould.dev", custom_domain = true }
]
